
services:
  db:
    image: postgres:latest
    container_name: go-social-db
    environment:
      POSTGRES_DB: go-social
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis: 
    image: redis:7.4-alpine
    container_name: go-social-redis
    command: redis-server --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # api:
  #   build: .
  #   container_name: go-social-api
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     DB_ADDR: "postgres://admin:adminpassword@db:5432/go-social?sslmode=disable"
  #     REDIS_ADDR: "redis:6379"
  #   ports:
  #     - "8080:8080"

    
volumes:
  db-data:
  redis-data:

# psql -h localhost -U admin -d go-social