// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: follows.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :exec
INSERT 
INTO follows (user_id, follow_id) 
VALUES ($1, $2)
`

type FollowUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FollowID uuid.UUID `json:"follow_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.UserID, arg.FollowID)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows 
WHERE user_id = $1 AND follow_id = $2
`

type UnfollowUserParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FollowID uuid.UUID `json:"follow_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.UserID, arg.FollowID)
	return err
}
