// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comments struct {
	ID        uuid.UUID `json:"id"`
	PostID    uuid.UUID `json:"post_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Follows struct {
	UserID    uuid.UUID `json:"user_id"`
	FollowID  uuid.UUID `json:"follow_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Posts struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Tags      []string  `json:"tags"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserInvitations struct {
	Token   uuid.UUID `json:"token"`
	UserID  uuid.UUID `json:"user_id"`
	Expiary time.Time `json:"expiary"`
}

type Users struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Username  string       `json:"username"`
	Password  []byte       `json:"password"`
	CreatedAt time.Time    `json:"created_at"`
	Verified  sql.NullBool `json:"verified"`
}
