// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package store

import (
	"context"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description 
FROM roles 
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Roles, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Roles
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
